import { FlowStep } from './types';

export const CHAT_FLOW: FlowStep[] = [
    {
        id: 'moodLevel',
        question: 'How is your mood right now? (1-10)',
        type: 'slider',
        field: 'status',
        subField: 'moodLevel',
        min: 1,
        max: 10,
    },
    {
        id: 'sleepQuality',
        question: 'How was your sleep quality? (1-10)',
        type: 'slider',
        field: 'status',
        subField: 'sleepQuality',
        min: 1,
        max: 10,
    },
    {
        id: 'sleepDuration',
        question: 'How many hours did you sleep?',
        type: 'slider',
        field: 'status',
        subField: 'sleepDuration',
        min: 0,
        max: 12,
    },
    {
        id: 'energyLevel',
        question: 'What is your energy level? (1-10)',
        type: 'slider',
        field: 'status',
        subField: 'energyLevel',
        min: 1,
        max: 10,
    },
    {
        id: 'stabilityScore',
        question: 'Rate your stability score (1-10)',
        type: 'slider',
        field: 'status',
        subField: 'stabilityScore',
        min: 1,
        max: 10,
    },
    {
        id: 'summary',
        question: 'Give a brief summary of your day/state.',
        type: 'text',
        field: 'summary',
    },
    {
        id: 'wins',
        question: 'List your wins for the day (separate by newlines or commas).',
        type: 'text',
        field: 'insights',
        subField: 'wins',
    },
    {
        id: 'losses',
        question: 'Any losses or challenges?',
        type: 'text',
        field: 'insights',
        subField: 'losses',
    },
    {
        id: 'ideas',
        question: 'Any new ideas?',
        type: 'text',
        field: 'insights',
        subField: 'ideas',
    },
    {
        id: 'goals',
        question: 'What are your goals for tomorrow?',
        type: 'text',
        field: 'goals',
    },
    {
        id: 'tags',
        question: 'Add any tags (e.g., #work, #health).',
        type: 'text',
        field: 'tags',
    },
];
